title: "Roman's Blog"
description: "Elke dag een b'tje beter"
defaultTheme: "auto"
# website images for Open Graph and Twitter Cards
images: []

fingerprint: "sha512"
dateFormat: "02.01.2006"

author:
  name: "Roman Shopin"
  email: "shopin.roman@gmail.com"
  link: "/about"

app:
  title: "Roman's Blog"
  noFavicon: true
  svgFavicon:
  themeColor: "#ffffff"
  iconColor: "#5bbad5"
  tileColor: "#da532c"

header:
  desktopMode: "fixed"
  mobileMode: "auto"
  title:
    logo:
    name: "Roman's Blog"
    pre:
    post:
    typeit: false

footer:
  enable: true
  custom: ""
  hugo: true
  copyright: true
  author: true
  since: 2023
  icp: ""
  license: ""

section:
  paginate: 20
  dateFormat: "02.01"
  rss: 10

list:
  paginate: 20
  dateFormat: "02.01"
  rss: 10

search:
  enable: false

home:
  rss: 10
  profile:
    enable: true
    avatarURL: "/images/author/avatar.webp"
    title: ""
    subtitle: "Elke dag een b'tje beter"
    typeit: true
    social: true
    disclaimer: ""
  posts:
    enable: true
    paginate: 10

page:
  hiddenFromHomePage: false
  hiddenFromSearch: false
  twemoji: false
  lightgallery: false
  ruby: false
  fraction: false
  fontawesome: false
  linkToMarkdown: true
  rssFullText: false
  toc:
    enable: true
    keepStatic: false
    auto: true
  seo:
    images: []
    publisher:
      name: "Roman Shopin"
      logoUrl: "/images/author/avatar.webp"
  share:
    enable: true
    Twitter: true
    Facebook: true
    Linkedin: true
    Whatsapp: true
    Pinterest: true
    Tumblr: false
    HackerNews: false
    Reddit: true
    VK: false
    Buffer: false
    Xing: false
    Line: false
    Instapaper: true
    Pocket: true
    Flipboard: false
    Weibo: false
    Blogger: false
    Baidu: false
    Odnoklassniki: false
    Evernote: true
    Skype: false
    Trello: false
    Mix: false
  code:
    copy: true
    maxShownLines: 50
  comment:
    enable: false

social:
  GitHub: "devromans"
  Linkedin: "rshopin"
  Instagram: "devromans"
  Telegram: "krimzhel"
#  Medium: ""
#  Gitlab: ""
#  Soundcloud: ""
#  Spotify: ""
#  Strava: ""
  Email: "shopin.roman@gmail.com"
  RSS: ""
  Mastodon:
    id: "@devromans"
    prefix: "https://mastodon.social/"
    title: "Mastodon"

typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: "|"
  duration: -1

compatibility:
  polyfill: false
  objectFit: false

cookieconsent:
  enable: false
  content:
    message: ""
    dismiss: ""
    link: ""

analytics:
  enable: false
  umami:
    id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
seo:
  image: ""
  thumbnailUrl: ""

